# Generated by Django 4.2 on 2026-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sanpham_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
