# Generated by Django 4.2 on 2026-04-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='Category',
            field=models.ManyToManyField(related_name='sanpham', to='app.category'),
        ),
    ]
