# Generated by Django 4.2 on 2026-04-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sanpham_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanpham',
            old_name='Category',
            new_name='category',
        ),
    ]
