# Generated by Django 4.2 on 2026-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_category_sanpham_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
